In [1]:
from torch import nn
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        out = self.linear(x)
        return out
    
lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.6728]], requires_grad=True), Parameter containing:
tensor([-0.3366], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [2]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

count_parameters(lr)

2

In [3]:
count_parameters(nn.Linear(4, 1))

5

In [4]:
import torch 

X=torch.tensor([[1.0,1.0,1],[1.0,2.0,1],[1.0,3.0,1],[1.0,3.0,1]])

model=nn.Linear(3,1)

yhat=model(X)
yhat

tensor([[0.2854],
        [0.5589],
        [0.8325],
        [0.8325]], grad_fn=<ThAddmmBackward>)

In [5]:
z = torch.tensor([[1,0,-1],[2,0,-2],[1,0,-1]])
torch.nn.functional.relu(z)

tensor([[1, 0, 0],
        [2, 0, 0],
        [1, 0, 0]])

In [6]:
z = torch.tensor([[[1,2,3,-4],[0.0,2.0,-3.0,0],[0,2,3,1],[0,0,0,0]]])
max_ = torch.nn.MaxPool2d(2, stride=2)
max_(z)

tensor([[[2., 3.],
         [2., 3.]]])

In [7]:
z = torch.tensor([[2,5,0],[10,8,2],[6,5,1]])
_, yhat = z.max(1)
yhat

tensor([1, 0, 0])

In [11]:
q=torch.tensor(1.0,requires_grad=False)

fq=2*q**3+q

fq.backward()

q.grad

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
from torch.nn import Linear model=Linear(in_features=1,out_features=1)